language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - "export DISPLAY=:99.0"                                         # Required for graphics
  - "sh -e /etc/init.d/xvfb start"                                 # Required for graphics
  - wget https://julialang.s3.amazonaws.com/bin/linux/x64/0.3/julia-0.3.2-linux-x86_64.tar.gz
  - tar -xzvf julia-0.3.2-linux-x86_64.tar.gz
  - /home/travis/build/codles/Private.jl/julia-8227746b95/bin/julia -e 'Pkg.clone("git://github.com/codles/EEG.jl.git")'
  - /home/travis/build/codles/Private.jl/julia-8227746b95/bin/julia -e 'Pkg.clone("https://github.com/codles/MinMaxFilter.jl.git")'
  - /home/travis/build/codles/Private.jl/julia-8227746b95/bin/julia -e 'Pkg.clone("git@github.com:codles/Private.jl.git")'
script:
  - /home/travis/build/codles/Private.jl/julia-8227746b95/bin/julia -e 'Pkg.test("Private")'
