language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
sudo: true
before_install:
  - "export DISPLAY=:99.0"                                         # Required for graphics
  - "sh -e /etc/init.d/xvfb start"                                 # Required for graphics
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - sudo pip install --upgrade pip
  - sudo apt-get update
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-base-dev gfortran
  - pip install numpy scipy --user
  - pip install mne --user
  - julia -e 'Pkg.add("TimeModels"); Pkg.checkout("TimeModels")'
  - julia -e 'Pkg.clone("https://github.com/codles/EEG.jl.git"); Pkg.build("EEG")'
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Private"); Pkg.test("Private"; coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("Private")); Pkg.add("Coverage"); using Coverage; Codecov.submit_local(process_folder())'
