language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - pwd
  - wget https://julialang.s3.amazonaws.com/bin/linux/x64/0.3/julia-0.3.2-linux-x86_64.tar.gz
  - tar -xzf julia-0.3.2-linux-x86_64.tar.gz
  # - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.clone("git://github.com/codles/EEG.jl.git")'
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("Private")'
