language: julia
os:
  - linux
julia:
  # - 0.3
  - 0.4
notifications:
  email: false
sudo: true
before_install:
  - "export DISPLAY=:99.0"                                         # Required for graphics
  - "sh -e /etc/init.d/xvfb start"                                 # Required for graphics
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/codles/MinMaxFilter.jl.git")'
  - julia -e 'Pkg.add("DSP"); Pkg.checkout("DSP")'
  - julia -e 'Pkg.add("TimeModels"); Pkg.checkout("TimeModels")'
  - julia -e 'Pkg.add("SIUnits"); Pkg.checkout("SIUnits")'
  - julia -e 'Pkg.add("EEG"); Pkg.checkout("EEG"); Pkg.build("EEG")'
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Private"); Pkg.test("Private"; coverage=true)'
